apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-8hxf
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0075-tenant/tkrw-pr712-0075-0075-app/devfile-sample-8hxf@sha256:5ebd16ead2705b1d344cfbc95b432f99c58f161319f36673b276002674fc8fc8
        name: my-nodejs
        resources: {}
status: {}
